required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/gengo/examples/defaulter-gen/generators",
  "k8s.io/gengo/examples/deepcopy-gen/generators"
]

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-8.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  branch = "master"

[[constraint]]
  name = "github.com/coreos/dex"
  source = "https://github.com/jenkins-x/dex.git" 
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go=false
    go-tests = false
