// Code generated by lister-gen. DO NOT EDIT.

package v1

// SSOListerExpansion allows custom methods to be added to
// SSOLister.
type SSOListerExpansion interface{}

// SSONamespaceListerExpansion allows custom methods to be added to
// SSONamespaceLister.
type SSONamespaceListerExpansion interface{}
