// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/jenkins-x/sso-operator/pkg/client/clientset/versioned/typed/jenkins.io/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeJenkinsV1 struct {
	*testing.Fake
}

func (c *FakeJenkinsV1) SSOs(namespace string) v1.SSOInterface {
	return &FakeSSOs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeJenkinsV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
