{{ $fullname := include "fullname" . }}
  {{- if .Values.certs.legacyApi }}
apiVersion: certmanager.k8s.io/v1alpha1
  {{- else }}
apiVersion: cert-manager.io/v1alpha2
  {{- end }}
kind: Certificate
metadata:
  name: {{ $fullname }}-grpc-client-cert
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  secretName: {{ .Values.dex.certs.grpc.client.secretName }}
  issuerRef:
    name: {{ .Values.dex.certs.grpc.issuer.name }}
    kind: {{ .Values.dex.certs.grpc.issuer.kind }}
  commonName: dex-grpc-client
  dnsName:
  - {{ .Values.dex.grpcHost }}
