// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/jenkins-x/sso-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SSOs returns a SSOInformer.
	SSOs() SSOInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// SSOs returns a SSOInformer.
func (v *version) SSOs() SSOInformer {
	return &sSOInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
