// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	jenkinsiov1 "github.com/jenkins-x/sso-operator/pkg/apis/jenkins.io/v1"
	versioned "github.com/jenkins-x/sso-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jenkins-x/sso-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/jenkins-x/sso-operator/pkg/client/listers/jenkins.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SSOInformer provides access to a shared informer and lister for
// SSOs.
type SSOInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SSOLister
}

type sSOInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSSOInformer constructs a new informer for SSO type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSSOInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSSOInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSSOInformer constructs a new informer for SSO type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSSOInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JenkinsV1().SSOs(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JenkinsV1().SSOs(namespace).Watch(options)
			},
		},
		&jenkinsiov1.SSO{},
		resyncPeriod,
		indexers,
	)
}

func (f *sSOInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSSOInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sSOInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&jenkinsiov1.SSO{}, f.defaultInformer)
}

func (f *sSOInformer) Lister() v1.SSOLister {
	return v1.NewSSOLister(f.Informer().GetIndexer())
}
